version: '3'
services:
    php:
        build:
            context: ./docker/php
        image: php:8.1-fpm
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - app-network

    mysql:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - './docker/mysql/init.sql:/docker-entrypoint-initdb.d/dump.sql'
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
