CREATE DATABASE IF NOT EXISTS testtask;
USE testtask;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS link (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    link VARCHAR(255) NOT NULL,
    is_deactivated TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deactivated_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS game (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    random_number SMALLINT,
    win_sum SMALLINT,
    is_win_number TINYINT(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

